# Generated by Django 2.2.5 on 2019-11-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='departure_date',
            new_name='added_at',
        ),
        migrations.AddField(
            model_name='attachment',
            name='url',
            field=models.CharField(default='/', max_length=256),
        ),
        migrations.AddField(
            model_name='chat',
            name='id_group_chat',
            field=models.IntegerField(default=0),
        ),
    ]
