# Generated by Django 2.2.5 on 2019-11-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20191119_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_grout_chat',
            field=models.BooleanField(default=False),
        ),
    ]
