# Generated by Django 2.2.5 on 2019-11-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20191119_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
