# Generated by Django 2.2.5 on 2019-11-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_chat_last_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='is_grout_chat',
            new_name='is_group_chat',
        ),
    ]
