# Generated by Django 2.2.5 on 2019-11-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20191120_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id_group_chat',
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chats.Message'),
        ),
    ]
