# Generated by Django 2.2.5 on 2019-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sername', models.CharField(max_length=64)),
                ('nick', models.CharField(max_length=64)),
                ('avatar', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('reg_date', models.DateTimeField()),
                ('motto', models.CharField(max_length=128)),
            ],
        ),
    ]
